services:
  backend:
    image: ghcr.io/bepplinh/datban/backend:latest
    container_name: datban-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - datban-network

networks:
  datban-network:
    driver: bridge
